project:
  type: website
  output-dir: docs
  
website:
  title: "ChoiYunYu.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - today.qmd
      - theoretical.qmd

format:
  html:
    theme: solarized
    css: styles.css
    toc: true

editor: visual

