---
title: "My Dataset"
---

This dataset contained information about a sample of men and women and their cooking skills (rated on their own assumption), descriptive data of their demographics, marital status, salary and education.

The columns I specifically focused on were gender, age, marital status and their self-proclaimed cooking skills. The analysis of such relations is essential because it sheds light on societal norms, household dynamics, and individual perceptions. Understanding how these all intersect can provide insights into various aspects of daily life, such as gender norms within the division of labour and cultural expectations.

# Graphs

## Scatterplot Graph

This is a scatter graph illustrating self-rated cooking skills against age, with gender separated by colour. Women did not assess themselves below a six. Men were more scattered, albeit barely - a majority at the lower end of the scale with a few anomalies at 6, 8, and 10. (Hover over each point to better see the statistics of each point)

```{=html}
 <iframe height="600" width="100%" frameborder="no" src="https://choiyunyu.shinyapps.io/scattergraph/"> </iframe>
```
## Density Plot

This is a density plot illustrating the density of genders against self-rated cooking skills. We can see that women self-assess their cooking skills higher, with a majority self-ranking at 10. Men on the other hand have a mode at the lower end of the spectrum - 2.5 or 3.

```{=html}
 <iframe height="600" width="100%" frameborder="no" src="https://choiyunyu.shinyapps.io/density/"> </iframe>
```

```{=html} 
 <iframe height="600" width="100%" frameborder="no" src="https://choiyunyu.shinyapps.io/groupbar/"> </iframe>

```

# Reading the graphs
